name: pull request comment
on: 
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened
      - edited
jobs:
 job01:
   if: contains(github.event.comment.html_url, '/pull/')
   runs-on: ubuntu-latest
   steps:
    - name: triggered support
      if: contains(github.event.comment.body, '/support')
      run: |
       echo 'say hellsupport'