name: Pull request khan
on: 
  issue_comment:
    types:
      - created
      - edited
  discussion:
    types: 
    - created
    - edited
    - answered
  pull_request:
    types:
    - opened
    - edited
    - synchronize

jobs:
  runtest:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '#hello'
          reaction: eyes
          prefix_only: true
        env:
          GITHUB_TOKEN: '${{secrets.WORKFLOW_PERSONAL_TOKEN}}'
        if: steps.check.outputs.triggered == 'true'
      - run: echo 'hii. here I think goes the workflow'